# Create environment: conda env create --file environment.yml
# Activate environment: conda activate fys4411
# Deactivate environment: conda deactivate
# To remove environment: conda remove --name fys4411 --all
# To verify that the environment was removed: conda info --envs

name: fys4411
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - matplotlib
  - scipy
  - pandas
  - seaborn
  - jupyter
  - cython
  - pytest
  - autopep8
  - isort
  - yapf
  - scikit-learn
  - pip:
    - "jax[cpu]"
